Improve public key output and add file output
sigstore/sigstore-rs pull request #194
Opened 2023-01-16 20:17 UTC by Gronner

#### Summary

As described in #105 the output provided by the example `get_public_key` was not pretty. It included quotation marks at the beginning and the and, as well as the newline characters `\n`. 
In addition this prevented piping the output of the example into a file, as it would include the quotation marks and the newline characters. Now using `cargo run --example get_public_key > key.pub` the public key can be stored in a file in the PEM format.

In addition it can be useful to directly store the public key in a file instead of piping to a file.  

#### Release Note

The Rekor example `get_public_key` was expanded to:
* use `Display` printing 
* provide a command line option to store the public key in a file

#### Documentation

Close #105

2023-01-25 16:08 UTC, flavio requested changes

2023-01-25 16:08 UTC, flavio commented on examples/rekor/get_public_key/main.rs
> +        match write(out_path, pubkey.unwrap()) {
nitpicking: instead of using `unwrap` use `expect` with a nice message. I would do that right on line `50`, after the `await`.

2023-01-25 17:26 UTC, Gronner commented on examples/rekor/get_public_key/main.rs
> +        match write(out_path, pubkey.unwrap()) {
Done, in the future it might be useful to enhance the errors get_public_key returns to enhance the possible feedback or by "unpacking" the information stored in the returned error.

2023-01-26 07:54 UTC, flavio approved these changes

2023-01-26 08:08 UTC, merged