Update create_log_entry example to create key pair.
sigstore/sigstore-rs pull request #206
Opened 2023-02-01 19:00 UTC by jvanz

#### Summary

Updates the example program create_log_entry to create the key pair used to sign and upload the data file into the Rekor transparency log. Therefore, the users do not need to create the files and generate the hashes required to create an transparency log entry.

Fix #104

2023-02-07 07:59 UTC, flavio requested changes

2023-02-07 07:59 UTC, flavio commented on examples/rekor/create_log_entry/main.rs
> +async fn generate_keys() -> Result<(EcKey<Private>, String), ErrorStack> {
I think we don't have to deal with the low-level openssl libraries to do that. sigstore-rs recently gained the ability to [create signing keys](https://docs.rs/sigstore/0.6.0/sigstore/crypto/signing_key/index.html#simple-usages).

I **think** this should work for this use case. If that's the case, I would prefer this example to make use of our API

2023-05-09 15:04 UTC, flavio requested changes
overall ok, I left some minor comments

2023-05-09 15:04 UTC, flavio commented on examples/rekor/create_log_entry/main.rs
> +        .unwrap()
nitpicking: an expect would be better, since it would allow to provide some context about the failure

2023-05-09 15:04 UTC, flavio commented on examples/rekor/create_log_entry/main.rs
> +    //let keys_job = generate_keys();
if not used, remove it

2023-05-09 15:04 UTC, flavio commented on examples/rekor/create_log_entry/main.rs
> +    //let (key, public_key_base64) = keys_job.await.unwrap();
if not used, remove it

2023-05-18 13:19 UTC, flavio requested changes
LGTM, there's just one final comment to be fixed

2023-05-18 13:19 UTC, flavio commented on examples/rekor/create_log_entry/main.rs
> +    the pram will generate a key pair, download the file available at [TODO], sign it
nitpicking: can you address the TODO please?

2023-05-30 07:12 UTC, flavio submitted a review, later dismissed

2023-05-30 07:35 UTC, flavio submitted a review, later dismissed

2023-05-30 07:53 UTC, viccuad commented on examples/rekor/create_log_entry/main.rs
> +    the pram will generate a key pair, download the file available at URL constant, sign it
I think this should say "the program"

2023-05-30 07:54 UTC, viccuad commented on examples/rekor/create_log_entry/main.rs
> +    When you use the example code to create a new entry with fresh set of input values or levaing the program
typo: "or leaving"

2023-05-30 07:57 UTC, viccuad approved these changes
LGTM!

2023-05-30 08:06 UTC, flavio commented
@viccuad can you please approve again? I fixed the 2 typos you reported

2023-05-30 08:07 UTC, viccuad approved these changes
approved!

2023-05-30 08:44 UTC, merged