Add verify-blob example
sigstore/sigstore-rs pull request #239
Opened 2023-03-14 05:28 UTC by danbev

#### Summary

This commit adds a new example which verifies a blob created using cosign sign-blob. The function `SignedArtifactBundle::verify_blob` has been extracted and moved into the `cosign` module, which `SignedArtifactBundle::verify_blob` now calls.

#### Release Note

NONE

#### Documentation

NONE

2023-03-15 07:54 UTC, lukehinds reviewed
The example looks good, but we now have two `verify_blob` functions. Is the idea the code is better suited to being in mod rather than bundle.rs? Would like to understand the rationale there.

2023-03-16 04:29 UTC, danbev commented
> Is the idea the code is better suited to being in mod rather than bundle.rs? Would like to understand the rationale there.

I probably should have put this code in the `cosign` module instead of the `bundle` module (`SignedArtifactBundle::verify_bundle`) to begin with, but it was not until now I had the need to verify a blob without a bundle and thought it made sense to extract the code in common to both functions. I'd be happy to make changes if there is a better place for this.

2023-03-22 21:19 UTC, lkatalin commented
The example flow worked for me (some small comments inline) and I love the README - very clear!

Re: relocation of the `verify_blob()` function: I lean toward moving this to `mod.rs` the way this PR does, as it is cleaner conceptually since it may need to be called in both a bundle and non-bundle scenario. Making the `verify_blob()` in `bundle.rs` into a wrapper is slightly awkward, but taking it out of `bundle.rs` entirely makes the `verify-bundle` example do slightly more work - I don't have a strong opinion on that part.

I would say this is fine to merge, esp with small changes to the example's README. @lukehinds what do you think?

2023-03-23 06:16 UTC, danbev commented
@lkatalin Thanks for taking a look! 

> The example flow worked for me (some small comments inline)

I not exactly sure which comments this refers to. Can you point me to them and I'll address them. Thanks

2023-03-24 04:57 UTC, danbev commented on examples/cosign/verify-blob/README.md
> +COSIGN_EXPERIMENTAL=1 cosign sign-blob \
This is just me not keeping up with things. I'll install cosign 2.0 and make the changes :+1:

2023-03-24 04:58 UTC, danbev commented on examples/cosign/verify-blob/README.md
> +cd examples/cosign/verify-blob
Good point, I'll move this. Thanks

2023-03-24 05:01 UTC, danbev commented on examples/cosign/verify-blob/README.md
> +Verification succeeded
Good point! I'll remove the quiet flag instead :+1:

2023-03-24 07:21 UTC, danbev commented on examples/cosign/verify-blob/README.md
> +```
I'll update this section. Thanks!

2023-03-24 07:26 UTC, danbev commented on examples/cosign/verify-blob/README.md
> +This example shows how to verify a blob signature that was created by the
Added this now. Thanks

2023-03-24 10:42 UTC, lkatalin submitted a review, later dismissed
lgtm!

2023-03-24 11:13 UTC, lukehinds commented on src/cosign/bundle.rs
>      pub fn verify_blob(&self, blob: &[u8]) -> Result<()> {
This might be me not being to smart, but do we really need this replicated function. Why not call verify_blob in cosign/mod directly. I am sure there is some logic, just get me up to speed so I can understand.

2023-03-24 11:21 UTC, lkatalin commented on src/cosign/bundle.rs
>      pub fn verify_blob(&self, blob: &[u8]) -> Result<()> {
Calling it directly from cosign/mod is a completely valid alternative IMO. We would just need to update the cosign/verify-bundle example and it wouldn't be able to use `bundle.verify_blob()` anymore [here](https://github.com/sigstore/sigstore-rs/blob/main/examples/cosign/verify-bundle/main.rs#L63), so we might not even need to create the bundle to begin with in that example, as that was its only purpose.

2023-03-26 06:54 UTC, danbev commented on src/cosign/bundle.rs
>      pub fn verify_blob(&self, blob: &[u8]) -> Result<()> {
I've taken a look and this makes sense to me. I've updated with a new commit now.

2023-03-28 09:06 UTC, flavio requested changes
I left some comments. I would be fine to have this function defined inside of the `cosign` mod, like it currently is.

I wonder however if it wouldn't be better to move that into the `CosignCapabilities` trait.

2023-03-28 09:06 UTC, flavio commented on src/cosign/mod.rs
> +/// Verifies the blob using the signature, and the certificate.
I think the inline documentation should be more clear:

```suggestion
/// Verifies the signature produced by cosign when signing the given blob via the `cosign sign-blob` command
///
/// The parameters:
/// * `cert`: a PEM encoded x509 certificate that contains the public key used to verify the signature
/// * `signature`: the base64 encoded signature of the blob that has to be verified
/// * `blob`: the contents of the blob
///
/// This function returns `Ok())` when the given signature has been verified, otherwise returns an `Err`.
```

As a result of that, I think we can rename the `base64_signature` to be just `signature`.

2023-03-28 09:06 UTC, flavio commented on examples/cosign/verify-bundle/main.rs
> +        Err(_) => eprintln!("Verification failed"),
I would not hide the error. Getting an error does not automatically mean that the signature is not valid. There could be an issue parsing the certificate, the signature,...

2023-03-29 12:36 UTC, danbev commented
I'm working on a task where I'd like to use `verify_blob` but only using a public key and not a certificate. Would it make sense to add a function named something like `verify_blob_with_public_key` :
```rust
  ///                                                                                
  /// Verifies the signature produced by cosign when signing the given blob via the `cosign sign-blob` command 
  ///                                                                                
  /// The parameters:                                                                
  /// * `public_key`: the public key used to verify the signature                    
  /// * `signature`: the base64 encoded signature of the blob that has to be verified 
  /// * `blob`: the contents of the blob                                             
  ///                                                                                
  /// This function returns `Ok())` when the given signature has been verified, otherwise returns an `Err`. 
  pub fn verify_blob_with_public_key(public_key: &str, signature: &str, blob: &[u8]) -> Result<()> { 
      let ver_key =                                                                  
          CosignVerificationKey::try_from_pem(public_key.as_bytes()).expect("conversion failed");
      let signature = Signature::Base64Encoded(signature.as_bytes());                
      ver_key.verify_signature(signature, blob)?;                                    
      Ok(())                                                                         
  } 
```

2023-03-29 20:18 UTC, lkatalin commented
@danbev I think your `verify_blob_with_public_key()` function would make sense.

2023-03-30 13:27 UTC, lkatalin approved these changes

2023-03-31 05:31 UTC, danbev commented
@lkatalin Sorry about dismissing your review. I only rebased and squashed the commits related to the comments above.

2023-03-31 13:39 UTC, lkatalin approved these changes

2023-04-03 15:23 UTC, lkatalin commented
Actually, looking at @flavio 's comment, it looks like the `verify_blob_*` functions should move into the `CosignCapabilities` trait. @danbev Can you make this update? Hopefully then we will be good to go.

2023-04-04 13:59 UTC, lkatalin requested changes
@danbev I think the verification error reverted, I left a suggestion on there. That should hopefully be the last thing. :crossed_fingers:

2023-04-04 15:12 UTC, danbev commented on examples/cosign/verify-bundle/main.rs
> +        Err(_) => eprintln!("Verification failed"),
Sorry about that. I've updated this now. Thanks

2023-04-04 18:22 UTC, lkatalin approved these changes
LGTM! What do you think, @flavio ?

2023-04-06 08:14 UTC, flavio requested changes
Sorry for the delay, I left some comments

2023-04-06 08:14 UTC, flavio commented on src/cosign/mod.rs
> +    /// * `public_key`: the public key used to verify the signature
```suggestion
    /// * `public_key`: the public key used to verify the signature, PEM encoded
```

2023-04-06 09:40 UTC, danbev commented on src/cosign/mod.rs
> +        let ver_key = CosignVerificationKey::try_from(&spki).expect("conversion failed");
Ah sorry about that, I'll update shortly. Thanks!

2023-04-06 12:32 UTC, flavio approved these changes
thanks for the fixes

2023-04-06 12:33 UTC, merged

2023-04-06 12:39 UTC, danbev commented
@lkatalin @lukehinds @flavio Thanks for all your reviews and patience on this one!