Add functionality to make an entry in Rekor
sigstore/sigstore-rs pull request #26
Opened 2022-02-02 20:00 UTC by jyotsna-penumaka

Signed-off-by: jyotsna-penumaka <jpenumak@redhat.com>

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-02-04 16:31 UTC, jyotsna-penumaka commented
@lkatalin Thanks for the review.
Since we can only make a unique rekor entry, the test that is currently in the file passed (the request to make a rekor entry would return a Post struct) the first time (with fresh data - new file's hash and signature) but now it would fail (it would return an error). To test the code, you will have to use another file and its hash and signature. Do you have any recommendations for the tests to add?
I don't think there is more work to be done for the functionality of making a rekor entry.
I could add the functionality to get a rekor entry and the other cli commands in another pull request.

2022-02-04 17:58 UTC, lkatalin commented
> To test the code, you will have to use another file and its hash and signature. Do you have any recommendations for the tests to add?
I see why that's tricky. You would have to generate some new test data for each call to the test, instead of hardcoding it. You could have some function in the tests module `generate_test_data()` that echoes a randomly generated string to a file, signs that file ex. with `ssh-keygen`, and returns the path to the file and its signature file. Then you could upload those to Rekor, and remove the files you generated. Generating the data would almost make more sense to do in bash, though. Or maybe we don't need to get so complicated. @lukehinds Do you have any thoughts here? Is it enough to have Rekor say "this entry already exists" or do we want to fully test that we're uploading new entries?

> I could add the functionality to get a rekor entry and the other cli commands in another pull request.
Sounds good!

2022-02-05 06:59 UTC, lukehinds reviewed
A couple of comments made. One thing that might be useful is an entry in the examples folder.

2022-02-05 06:59 UTC, lukehinds commented on src/rekor.rs
> +    }
I don't think we need this?

2022-02-05 06:59 UTC, lukehinds commented on src/rekor.rs
> +            .unwrap();
I will take another look on Monday, but we might be able to trim these unwraps with a question mark operator

2022-02-05 07:03 UTC, lukehinds commented
> > To test the code, you will have to use another file and its hash and signature. Do you have any recommendations for the tests to add?
> 
> I see why that's tricky. You would have to generate some new test data for each call to the test, instead of hardcoding it. You could have some function in the tests module `generate_test_data()` that echoes a randomly generated string to a file, signs that file ex. with `ssh-keygen`, and returns the path to the file and its signature file. Then you could upload those to Rekor, and remove the files you generated. Generating the data would almost make more sense to do in bash, though. Or maybe we don't need to get so complicated. @lukehinds Do you have any thoughts here? Is it enough to have Rekor say "this entry already exists" or do we want to fully test that we're uploading new entries?
> 
> > I could add the functionality to get a rekor entry and the other cli commands in another pull request.
> 
> Sounds good!

Ideally we should test for both new entry and existing entry. Maybe I have not fully grasped the issues here, but we could have to sets of signing materials in a json file, that we parse for both tests?

2022-02-07 16:37 UTC, flavio requested changes
I feel sorry about the number of comments I left, I hope you won't mind :sweat_smile:

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +    }
I agree, I don't think sigstore-rs should provide this helper. IMHO it's up to the developers using the library to provide their token (which could be obtained by them, inside of their code, using something like this code you wrote).

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +    pub struct Root {
I think it would make sense to provide a custom implementation of the `Default` trait, so that certain types have a meaningful value. For example, `api_version` and `kind` have probably something well known.

If that's the case, these values should be defined via constants

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +    ) -> Result<Post, serde_json::Error> {
This is a matter of personal taste, I don't like functions with many parameters to be exposed to the end users. This can get confusing.

What about using the [builder pattern](https://rust-unofficial.github.io/patterns/patterns/creational/builder.html) (see the cosign::ClientBuilder as another example).

We could have a `RootBuilder` struct, that builds `Root` objects based on a mix of default values and the values provided by the user.

Then we could have a `RekorClient` struct which has a `submit(root: &Root) -> crate::errorsResult<Post>` method.

The `RekorClient` could then take care of creating the reqwest client using the right set of attributes. Right now we will probably use the default params (like you're doing), but this architecture would allow us - if needed - to fine tune the rekor client to do things like:
  * talk with a different Rekor server - for people running their infra (this could be useful also for end to end tests)
  * load additional trusted CAs and do other tuning required to talk with "self-hosted" Rekor server

Most important of all, we can have a mock reqwest client to avoid direct interactions with the real Rekor server during our unit tests.

2022-02-07 16:37 UTC, flavio commented on Cargo.toml
> +openssl-probe = "0.1.5"
I don't think we need this crate, certificates are already found by openssl-sys and rustls.

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +        println!();
Do not use `println`, use `tracing` like inside of other parts of the library. When producing traces please use structured logging too.

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +        let v: Result<Post, serde_json::Error> = serde_json::from_str(&sum);
I'm a bit lost, are you parsing the json response manually?

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +    pub struct Post {
I think a better name for that could be `LogEntry`. The name is based on what rekor uses internally, unless I got it wrong by looking inside of rekor's [code](https://github.com/sigstore/rekor/blob/main/pkg/generated/models/log_entry.go#L36)

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +    pub struct Root {
Now that I got to the end of the PR, and looked at the rekor source code, this seems to be the most generic [ProposedEntry](https://github.com/sigstore/rekor/blob/3c0d61f848b7e22277f1cefb8d15c896917fdcf3/pkg/api/entries.go#L147).

Should we rename `Root` to be `ProposedEntry`? Maybe in the future, not right now, we could have a trait and then have one struct per type that we support, something like [rekor does](https://github.com/sigstore/rekor/blob/main/pkg/types/README.md)

2022-02-07 16:37 UTC, flavio commented on src/rekor.rs
> +        let _new_post = rekor_upload(
As said before, I would not hit the real rekor server inside of the unit tests. We should instead use a mock to simulate it.

2022-02-07 18:40 UTC, lkatalin commented on src/rekor.rs
> +        let _new_post = rekor_upload(
> As said before, I would not hit the real rekor server inside of the unit tests. We should instead use a mock to simulate it.

This is a good suggestion, and it should let us avoid having to generate new test data for each time we run the unit tests. So @jyotsna-penumaka, please ignore my previous comment about generating the data.

2022-02-07 18:43 UTC, lukehinds commented on src/rekor.rs
> +        let _new_post = rekor_upload(
ah I just groked while you @ mentioned me now about dupe entries, I did not spot this was against a live server. +1 to mocking

2022-02-13 01:08 UTC, lukehinds commented on Cargo.toml
> +httpmock = "0.6"
we should be able to move this under dev-dependencies.

2022-02-14 16:52 UTC, jyotsna-penumaka commented on Cargo.toml
> +httpmock = "0.6"
I added it to dev-dependencies now.
I moved the rekor_upload function that creates the mock server and send the request inside mod tests.

2022-02-14 19:24 UTC, jyotsna-penumaka commented on src/rekor.rs
> +mod tests {
Thank you for the advice!
`cargo doc --open` is a very nice feature.
I added documentation for the functions and the structs.

2022-02-14 19:28 UTC, jyotsna-penumaka commented on src/rekor.rs
> +    pub struct Root {
I thought renaming `Root` to `Rekord` would make more sense, since this request body corresponds to a Rekord entry.
I used the builder pattern like you suggested and initialized `api_version`, `kind` in `Rekord` and `format` in `Signature` and `algorithm` in `Hash` structs with the default values.

2022-02-14 19:33 UTC, jyotsna-penumaka commented on src/rekor.rs
> +    ) -> Result<Post, serde_json::Error> {
Yeah I completely agree, builder pattern looks much cleaner and is easier to understand :)

I used the builder pattern for the Rekord struct but I am not very clear on the RekorClient.
Is the idea to create a RekorClient struct, where a user can specify the server they want to make the request to?

2022-02-14 19:36 UTC, jyotsna-penumaka commented on src/rekor.rs
> +        let v: Result<Post, serde_json::Error> = serde_json::from_str(&sum);
We need to modify the response before we can read it into a Struct
This is the response that is returned by Rekor:

        {
            "9bf4f37447a48848c1f69b6463190cd6cef7728d6b86b7723f08aad0c54cb8d4": {
                "body": "eyJhcGlWZXJzaW9uIjoiMC4wLjEiLCJraW5kIjoicmVrb3JkIiwic3BlYyI6eyJkYXRhIjp7Imhhc2giOnsiYWxnb3JpdGhtIjoic2hhMjU2IiwidmFsdWUiOiI0NmJkMzE5ZDM1OTBkMmI0ZDdjN2EyN2M5OWQzMmY3ZWE2MGE4NTBlYzM4MDYzNTFlMDRkMTYxZDAxNGVjYzAxIn19LCJzaWduYXR1cmUiOnsiY29udGVudCI6IkxTMHRMUzFDUlVkSlRpQlRVMGdnVTBsSFRrRlVWVkpGTFMwdExTMEtWVEZPU1ZVd2JFaEJRVUZCUVZGQlFVRkVUVUZCUVVGTVl6Tk9iMHhYVm10TmFsVXhUVlJyUVVGQlFXY3ZkbVZUWXpSdmJIQkxkRTF2VDFJM2NuZG1PQXBXUjBoNmFHaG5NRVpKYjBSMFl6VlNNa3BzZEhwSFowRkJRVUZGV20xc2MxcFJRVUZCUVVGQlFVRkJSMk15YUdoT1ZFVjVRVUZCUVZWM1FVRkJRWFI2Q21NeVozUmFWMUY1VGxSVmVFOVJRVUZCUlVKalEydDBaME14V1dwcmIzZEtkSEJzZVhCRFNEUTJhbkV5UW1Sb05tUjZhblIwZVd0SFpWRjVLMG8xZUhvS2RIRlVlbXRqUXpCWVNHRkZZWEZPZFdNMWNURnpUbEZNWTJRNFNEUjRNM0ZLU2xSRFFsRnZUd290TFMwdExVVk9SQ0JUVTBnZ1UwbEhUa0ZVVlZKRkxTMHRMUzBLIiwiZm9ybWF0Ijoic3NoIiwicHVibGljS2V5Ijp7ImNvbnRlbnQiOiJjM05vTFdWa01qVTFNVGtnUVVGQlFVTXpUbnBoUXpGc1drUkpNVTVVUlRWQlFVRkJTVkEzTTJ0dVQwdEtZVk55VkV0RWEyVTJPRWd2UmxKb09EUlpXVTVDVTB0Qk4xaFBWV1JwV21KamVHOEsifX19fQ==",
                "integratedTime": 1643749079,
                "logID": "c0d23d6ad406973f9559f3ba2d1ca01f84147d8ffc5b8445c224f98b9591801d",
                "logIndex": 1236200,
                "verification": {
                    "signedEntryTimestamp": "MEQCID3QHHXwGauKUfFvs0YCMKZ4e3BE1ZIhrJ5RHnoHGophAiA/R5cDc8JnSUq6F7U/8oTk8/mn7QCdDXI+NRT7qm78+Q=="
                }
            }
        }
        
Since there is no member called "uuid" in the json body,
we cannot read it into the LogEntry struct.
So we add "{\"uuid\": " to the returned response and make it a valid json

2022-02-14 19:42 UTC, jyotsna-penumaka commented on src/rekor.rs
> +    ) -> Result<Post, serde_json::Error> {
I think the CI clippy test seems to run into an error when the new function returns the builder and now self.

2022-02-14 19:54 UTC, jyotsna-penumaka commented
Thank you @flavio , @lukehinds and @lkatalin for the detailed suggestions.
They were very helpful!

2022-04-04 06:29 UTC, lukehinds commented
shall we close this now that you have your crate @jyotsna-penumaka ?

2022-04-04 06:30 UTC, lukehinds commented
To add though, we should have something in examples/ or even a light client implementation.

2022-04-04 19:26 UTC, jyotsna-penumaka commented
@lukehinds I agree, I think we should close this.
I will add the examples to this repo once I publish the crate.

2022-04-04 19:26 UTC, closed without merging