cosign: Allow use of regex in CertSubjectEmailVerifier
sigstore/sigstore-rs pull request #300
Opened 2023-09-18 13:18 UTC by dave-tucker

#### Summary

This allows for either an exact match (via StringVerifier) or it allows for a regular expression match (via RegexVerifier).

This supports the use case of trusting signatures from a collection of email addresses e.g .*@redhat.com and or from a collection of issuers.

Fixes: #299

#### Release Note

- `CertSubjectEmailVerifier` is now constructed using either a `StringVerifer` for exact matches, or a `RegexVerifier` for cases where a pattern match is required. 

#### Documentation

Docstrings and examples are updated to show how this is used.

2023-09-20 12:58 UTC, flavio reviewed
I like the idea, I'm in favor of implementing this change.

The code looks good, but I have some suggestions. These might be a matter of personal taste, hence I'm open to have a discussion about how to proceed.

My proposal would be to change the `StringVerifier` from being a trait to be a simple enum. We could have something like `StringVerifier::ExactMatch(String)` and `StringVerifier::Regex(Regex)`. This would make the code easier to understand for our end consumers and we could get rid of the dynamic dispatch introduced by the usage of the trait.

What do you think?

2023-09-20 19:44 UTC, dave-tucker commented
> I like the idea, I'm in favor of implementing this change.
> 
> The code looks good, but I have some suggestions. These might be a matter of personal taste, hence I'm open to have a discussion about how to proceed.
> 
> My proposal would be to change the `StringVerifier` from being a trait to be a simple enum. We could have something like `StringVerifier::ExactMatch(String)` and `StringVerifier::Regex(Regex)`. This would make the code easier to understand for our end consumers and we could get rid of the dynamic dispatch introduced by the usage of the trait.
> 
> What do you think?

Makes sense to me. I've updated the patch with your proposal.

2023-09-21 15:12 UTC, flavio requested changes
I like it, thanks for having done the proposed change.

Aside from the nitpick comment (which would be great to see addressed, but I don't consider that mandatory), can you please address the inline docs feedback please?

2023-09-21 15:12 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +}
Can you add some inline docs to be included on docs.rs please?

2023-09-21 15:12 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +    fn cert_email_verifier_only_email_regex() {
nitpicking, using something like `rstest` could reduce a lot of this repetitions

2023-09-21 15:12 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +    fn cert_email_verifier_email_and_issuer_regex() {
same here

2024-09-20 07:23 UTC, flavio approved these changes
I realized this PR got stuck. I solved the conflicts with the `main` branch.

I'll merge it once all the tests are green

2024-09-20 07:24 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +    fn cert_email_verifier_only_email_regex() {
I was wrong, it's not easy to blend the two tests with rstest

2024-09-20 07:24 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +    fn cert_email_verifier_email_and_issuer_regex() {
I was wrong, it's not easy to blend the two tests with rstest

2024-09-20 07:24 UTC, flavio commented on src/cosign/verification_constraint/cert_subject_email_verifier.rs
> +}
Looking back, that's not really needed

2024-09-20 07:25 UTC, flavio commented
@Xynnn007 can you please give me an approval? I had to fix the conflicts with the `main` branch, but I didn't do any change to the original code submitted by @dave-tucker

2024-09-20 07:32 UTC, Xynnn007 approved these changes

2024-09-20 07:41 UTC, flavio commented
@Xynnn007 thanks!

@dave-tucker sorry about the delay!

2024-09-20 07:41 UTC, merged