cosign/tuf: use trustroot
sigstore/sigstore-rs pull request #305
Opened 2023-11-06 10:16 UTC by jleightcap

#### Summary

Towards #280, adapt Cosign and TUF to use trustroot.

As a roadmap, this PR is structured:
-  define the TUF trustroot types in `src/tuf/repository_helper.rs`.
- refactor the TUF implementation to use trustroot and rustls-webpki+rustls-pki-types.
  - note: this now means that the trustroot is "prefetch"ed, then used in async contexts--see release notes.
  - this also introduces some lifetime information that propagates into other components.
- misc. cleanup in changed components
  - pull the root JSON out of raw strings and into their own committed files.
  - `Repository` construction now uses the trustroot, with a `FakeRepository` option for BYO keys/certs--see release notes.

#### Release Note

The method of constructing a Repository with out-of-band trust materials (from Rekor public key and Fulcio certificate) has changed. See Cosign's verify example: https://github.com/sigstore/sigstore-rs/blob/a536beaa6c393e85e07f1d54cf01a4c7b2ec0258/examples/cosign/verify/main.rs#L231-L265 

And the signature verification documentation: https://github.com/sigstore/sigstore-rs/blob/8a269a304c3b3ed1c3a6c89e4a6a88f9af22598a/src/lib.rs#L83-L103

#### Documentation

2023-11-06 15:47 UTC, woodruffw commented
> @woodruffw and @tnytown mentioned some ownership design considerations that I'm not sure I fully understood. A closer look at some lifetime choices e.g.

@tnytown can confirm, but I believe the question was whether it makes sense to allow the interior `'a` lifetime on `CertificateDer<'a>` to "cascade" throughout the refactor. The alternative would be to create an `OwnedCertificateDer` wrapper that maintains a self-reference, using a crate like [`self_cell`](https://docs.rs/self_cell/latest/self_cell/).

This is exactly what PyCA Cryptography does, turning a `Certificate<'a>` into an `OwnedCertificate`:

https://github.com/pyca/cryptography/blob/4c07d8eb289aaa0fbcdbcf370724122905fade02/src/rust/src/x509/certificate.rs#L29C1-L36

Whether or not this actually makes sense to do, however, is ultimately a design question. If the `sigstore-rs` maintainers are okay with the lifetime, then it probably doesn't make sense to do 🙂

2023-11-09 16:55 UTC, lukehinds submitted a review, later dismissed
First pass looks good to me.

2023-11-09 16:55 UTC, lukehinds commented on src/tuf/trustroot.rs
> +#![allow(dead_code)]
Would be nice to get some doc comments we can render on https://docs.rs/sigstore

For an example:  https://github.com/sigstore/sigstore-rs/blob/7b61297217d8ac40058903abad278401bb20bfee/src/cosign/mod.rs#L16-L37

2023-11-10 08:18 UTC, flavio requested changes
It looks good to me. I left some minor comments.

There's just one major objection I have: the usage of the `rustls-webpki` crate.  This brings back the `ring` dependency which was removed by @Xynnn007 sometimes ago.

@Xynnn007 what do you think about that?

2023-11-10 08:18 UTC, flavio commented on src/tuf/mod.rs
> +            println!("data:\n{}", String::from_utf8_lossy(&data));
leftover, use a `debug!` statement please

2023-11-10 08:18 UTC, flavio commented on Cargo.toml
> +x509-cert = { version = "0.2.2", features = ["builder", "pem", "std"] }
When are we using the builder capabilities? Is that done inside of the tests? Sorry, I couldn't spot that while reviewing the code

2023-11-10 08:39 UTC, Xynnn007 commented on Cargo.toml
> +rustls-webpki = { version = "0.102.0-alpha.4", features = ["alloc"] }
At that time `ring v0.16.20` couldnot be built on `s390x`. After `ring 0.17.0` it could. `rustls-webpki v0.102.0-alpha.4` [has imported](https://github.com/rustls/webpki/blob/v/0.102.0-alpha.4/Cargo.toml#L78) `ring 0.17.0` so it would be fine.

2023-11-11 04:40 UTC, woodruffw commented on src/tuf/mod.rs
> +pub struct FakeRepository<'a> {
Agreed; `OfflineRepository` or similar makes more sense to me.

2023-11-14 07:41 UTC, flavio commented on src/tuf/mod.rs
> +            tough::RepositoryLoader::new(constants::SIGSTORE_ROOT, metadata_base, target_base)
Yes, let's address the switch to tough 0.15 to a dedicated PR.

I'm also fine with the changes done to the inline docs, thanks for the explanation.

2023-11-14 07:51 UTC, flavio approved these changes
Thanks for the contribution and for having gone through the requested changes

2023-11-14 07:51 UTC, merged