verify: init
sigstore/sigstore-rs pull request #311
Opened 2023-11-16 18:38 UTC by jleightcap

#### Summary

Complementary half of #310, enable the verification of bundles:

```sh
$ cargo run --manifest-path tests/conformance/Cargo.toml -- sign-bundle --bundle bundle.txt.sigstore --identity-token $(sigstore-python get-identity-token) bundle.txt
# ...
Operation succeeded!
$ cargo run --manifest-path tests/conformance/Cargo.toml -- verify-bundle --bundle bundle.txt.sigstore --certificate-identity jack@leightcap.com --certificate-oidc-issuer https://github.com/login/oauth bundle.txt
# ...
Operation succeeded!
```

#### Release Note

#### Documentation

2024-01-16 20:42 UTC, woodruffw requested changes

2024-01-16 20:42 UTC, woodruffw commented on src/verify/verifier.rs
> +        }
This is already covered by `store.verify_cert_with_time` above, so I think it can be removed outright.

2024-01-16 20:42 UTC, woodruffw commented on src/verify/verifier.rs
> +        }
This check should be unnecessary, since chain building (above) should assert that the leaf contains a `keyUsage.digitalSignature`.

2024-01-23 22:33 UTC, woodruffw commented on src/verify/models.rs
> +        };
I'm having a little trouble following this: why do we put `LogEntry` into a `OnceCell`, rather than just keeping it as `Option<LogEntry>` with a `None` variant when we're missing an entry?

2024-01-23 22:37 UTC, woodruffw commented on src/bundle/mod.rs
> +pub(crate) use required;
IMO this macro's usages are pretty hard to read -- I think we'd possibly be better off unfolding these inline (or using more bindings to minimize the number of error sites), plus implementing `TryInto` or another conversion trait where appropriate.

2024-02-14 22:25 UTC, jasperpatterson reviewed
I was playing around with these changes as I'm excited to see this functionality merged and noticed a couple little issues in my testing.

2024-02-14 22:25 UTC, jasperpatterson commented on src/verify/models.rs
> +        for chain_cert in chain_certs {
Should the `chain_certs` be added to the `VerificationMaterials`? It appears they are thrown away right now and chain verification does not currently work if intermediates are present.

2024-02-14 22:25 UTC, jasperpatterson commented on src/verify/models.rs
> +                signed_entry_timestamp: required!(; inclusion_promise.signed_entry_timestamp)?
I believe this is _not_ required for v0.2+ bundles? https://github.com/sigstore/protobuf-specs/blob/aa56b9a4929364918688fc7eeec3724c9941ddf9/protos/sigstore_rekor.proto#L105

2024-02-14 22:25 UTC, jasperpatterson commented on src/crypto/certificate.rs
> +                "invalid X.509 certificate: non-critical BasicConstraints in CA".to_string(),
In `src/verify/models.rs`, you're checking for an `Ok` result from this function, to determine whether what is expected to be an end certificate may unexpectedly be a root:

```rust
if is_root_ca(chain_cert).is_ok() {
    return None;
}
```

However this situation is valid for an end certificate, and not an error:

https://www.rfc-editor.org/rfc/rfc5280#section-4.2.1.9
> This extension MAY appear as a critical or non-critical extension in end entity certificates.

2024-02-14 22:38 UTC, jasperpatterson commented on src/verify/models.rs
> +            if is_root_ca(chain_cert).is_ok() {
I think you need to specifically check the bool here, not just for `Ok`.

2024-02-22 23:04 UTC, tannaurus commented on src/verify/verifier.rs
> +        if let Some(err) = policy.verify(&materials.certificate) {
Is there a particular reason this doesn't return `Result<(), PolicyError>`?

2024-02-22 23:15 UTC, tannaurus commented on src/verify/models.rs
> +        };
From our perspective, returning an error here would be really helpful. We have strict rules on what can and can't be logged, so the errors emitted here won't be captured. Returning error variants here would allow us to decide what gets logged, giving us the visibility that the `error!` had originally intended to provide 😄

2024-02-23 00:08 UTC, tannaurus commented on src/verify/verifier.rs
> +            .expect("Failed to construct certificate pool");
The outcome of `cert_pool()` is dependent upon the caller's implementation of `Repository`. `Repository` is a public trait that suggests it's ok to return a Result from `fulcio_certs()`

```
pub trait Repository {
    fn fulcio_certs(&self) -> Result<Vec<CertificateDer>>;
    fn rekor_keys(&self) -> Result<Vec<&[u8]>>;
}
```

There is no indication there that returning an error from `fulcio_certs` will cause `verify` to panic. Can this propagate the error instead?

2024-02-23 00:25 UTC, tannaurus commented on src/verify/models.rs
> +        };
Thanks! We (1Password) have to handle tracing with a lot more caution than many do due the type of data our applications are processing (lots of secrets). For that reason, we make sure only crates we've authored can emit trace events. In addition to that, only data that implements a special "Loggable" trait can be logged, allowing us to tie some compile time guarantees into what is safe and what isn't safe to be logged. 🔒 

This is great for our users (there secrets don't end up in our logs) but it does mean we end up wiring up some extra error handling code when working with third party crates ❤️

2024-02-23 00:32 UTC, tannaurus commented on src/verify/verifier.rs
> +        let Ok(signing_key): SigstoreResult<CosignVerificationKey> =
Please forgive the nits 👀 there's a bunch of places here where `map_err` could be used instead 😄 I don't have much skin in the game of this code base, just thought I'd share because I've found `map_err` to be a nice and reliable friend ❤️

2024-02-23 10:25 UTC, flavio reviewed
That's a big one :)

Sorry for the delay with the review. Overall looks fine to me, I left some comments.

2024-02-23 10:25 UTC, flavio commented on src/verify/verifier.rs
> +            .expect("Failed to construct certificate pool");
I agree with @tannaurus

2024-02-23 10:25 UTC, flavio commented on src/verify/verifier.rs
> +        let Ok(signing_key): SigstoreResult<CosignVerificationKey> =
I agree with @tannaurus

2024-02-23 16:07 UTC, woodruffw commented on src/verify/verifier.rs
> +        let Ok(signing_key): SigstoreResult<CosignVerificationKey> =
@tannaurus no need to apologize, the nits are greatly appreciated! `map_err` is definitely more idiomatic here.

2024-02-23 17:38 UTC, tannaurus commented on src/verify/models.rs
> +            return None;
This is always going to construct VerificationMaterials, unless it determines it wasn't provided the necessary data to do so. That feels like a case where we should be returning a `Result` instead. What do you think?

2024-02-24 16:20 UTC, tannaurus commented on src/bundle/mod.rs
> +                json_syntax::to_value(value.body).expect("failed to parse constructed Body!");
Can this propagate the error was well? This is implemented on two public structs 😄

2024-02-24 16:40 UTC, tannaurus commented on src/crypto/certificate.rs
> +    // that we won't consider the certificate a valid non-CA leaf.
This may be my morning brain or perhaps a lack of understanding, but I'm having a hard time understanding the last few words of this sentence. I would expect it to read

> Any other combination of states is inconsistent and invalid, meaning  that we won't consider the certificate a valid CA.

2024-02-24 16:41 UTC, tannaurus commented on src/crypto/certificate.rs
> +
For what it's worth, I like it 😄 it opens up the door for strong unit testing.

2024-02-24 16:50 UTC, tannaurus commented on src/crypto/certificate.rs
> +    Err(NotCAErrorKind::Invalid { ca, key_cert_sign })?
In what scenario would this occur? Is there something preventing us from just assert `!ca || !key_cert_sign` on line 278?

```
    if !ca  || !key_cert_sign {
        Err(NotCAErrorKind::NotCA)?;
    }
```

It would be nice to see all validation asserts get checked _before_ we have a path that returns Ok

2024-02-24 16:56 UTC, tannaurus commented on src/crypto/certificate.rs
> +    if tbs.issuer == tbs.subject {
Tiny suggestion 😄 
```suggestion
    if tbs.issuer != tbs.subject {
      Err(NotCAErrorKind::NotRootCA)?
    }
    
    Ok(())
```

2024-02-24 17:20 UTC, tannaurus commented on src/crypto/certificate_pool.rs
>          untrusted_intermediates: I,
Something I noticed while digging around: there doesn't appear to be support for `untrusted_intermediates` anywhere. (All invocations of `from_certificates` provide an empty slice). That appears to be the case dating back to November of last year, [here](https://github.com/sigstore/sigstore-rs/pull/305/files)

2024-02-26 22:56 UTC, woodruffw commented on src/crypto/certificate_pool.rs
>          untrusted_intermediates: I,
Yeah, there's no function for untrusted intermediates in the public instance of Sigstore: the trust root (that gets delivered through TUF or however else) constitutes the ultimate trust anchor, and it has the intermediates baked into it directly. 

(The only scenario in which untrusted intermediates make sense is a BYO PKI setup of Sigstore, where the trust root isn't complete and instead each signing cert is accompanied by one or more intermediates for chain construction purposes.)

2024-03-02 18:29 UTC, tannaurus commented on Cargo.toml
> -serde_with = { version = "3.4.0", features = ["base64"] }
This is only used in the `fulcio` module (behind the `fulcio` feature), maybe we can tuck that behind the `fulcio` feature?

2024-03-02 18:43 UTC, tannaurus commented on src/crypto/verification_key.rs
> +    pub fn verify_prehash(&self, signature: Signature, msg: &[u8]) -> Result<()> {
Something we may want to consider as we move forward to 1.0

Many of these functions don't strike me as something that needs to be `pub`. This function is an example of that. The one place this is called constructs this function's signature argument as `Signature::Raw`, but here we're left to account for `Signature::Base64Encoded` despite it seemingly not being a viable code path.

The primary concern I have with exposing functions like these are
1. it makes understanding the crate's usage more difficult than it needs to be, where the crate's documentation is populated with structs and functions that are not useful for any downstream dependents
2. Most critically: it makes everything we do a breaking change. As soon as something is `pub`, we must assume a downstream dependent is using this function with it's current function signature. Abiding by semver semantics becomes very difficult if not impossible.

2024-03-02 18:45 UTC, tannaurus commented on src/errors.rs
> +    InvalidCertError(String),
Doesn't look like this is used anywhere 👀

2024-03-02 18:59 UTC, tannaurus commented on src/fulcio/models.rs
> +    // The first two bytes indicate the signature and hash algorithms so let's skip those.
Is this not something we should verify is consistent with what we are expecting here? The leading two bytes are dropped from memory here so that source of truth is gone

2024-03-02 19:01 UTC, tannaurus commented on src/fulcio/models.rs
> +    let signature_size = u16::from_be_bytes(buf[2..4].try_into().expect("unexpected length"));
could this just be `usize::from_be_bytes`?

2024-03-02 19:03 UTC, tannaurus commented on src/lib.rs
> +#[cfg(feature = "bundle")]
Out of curiosity, what is the motivation behind adding this feature flag?

2024-03-02 19:17 UTC, tannaurus commented on src/verify/policy.rs
> +            .expect("failed to parse constructed Extension!");
Since these are pub traits/structs, it feels like we should be propagating this error. Is there a reason we're not?

2024-03-02 19:21 UTC, tannaurus commented on src/verify/verifier.rs
> +            .expect("failed to DER-encode constructed Certificate!")
Is there a particular reason this is safe to do?

2024-03-02 19:30 UTC, tannaurus commented on src/tuf/mod.rs
> +    /// let repo: Result<SigstoreRepository> = spawn_blocking(|| Ok(SigstoreRepository::new(None)?)).await?;
nit; now that `prefetch` is removed, this comment is only telling the caller how to use `spawn_blocking` which doesn't feel _super_ helpful

2024-03-02 19:33 UTC, tannaurus commented on src/tuf/mod.rs
> +    pub fn new(checkout_dir: Option<&Path>) -> Result<Self> {
nit; this is hiding an allocation (line 127). Feels like we can make that clearer to that caller by asking them to provide `Option<PathBuf>` which would allow them to make their own memory management decisions.

2024-03-02 19:39 UTC, tannaurus commented on src/tuf/mod.rs
> +        } else if let Some(embedded_data) = constants::static_resource(name.raw()) {
The other invocation of `static_resource` (with `root.json`) panics if it returns `None`. The only place `fetch_target` is invoked is where `name` equals `trusted_root.json`, which from what I can tell should be just as reliably available as as `root.json` is.

What makes `trusted_root.json` different from `root.json`? Is panicing if `root.json` is missing the wrong thing to do?

2024-03-02 19:48 UTC, tannaurus commented on src/tuf/mod.rs
> +        let data = if let Some(Ok(local_data)) = local_path.as_ref().map(std::fs::read) {
We're asking the caller to tell us where the disk cache is, but we're not communicating our failure to read from that cache. imo this error should be propagated to the caller because it indicates they've provided a bad argument. If we don't tell them that, someone could call `SigstoreRepository::new(whoops_not_a_real_dir)`, thinking it is reading from a local cache but it's actually reading from a remote target.

2024-03-02 19:55 UTC, tannaurus commented on src/tuf/mod.rs
> +            let _ = std::fs::write(local_path, &data);
shouldn't we handle this Result? (re: [my other comment](https://github.com/sigstore/sigstore-rs/pull/311/files#r1510028139))

2024-03-02 20:08 UTC, tannaurus commented on src/tuf/mod.rs
> +    fn fetch_target<N>(
_highly_ personal nit incoming

Lately I've been working with AWS Nitro Enclaves which don't have access to the disk, you're only option for caching is to keep things in memory. While I don't expect that to have a tangible impact on the changes proposed here, I just wanted to call that to attention: someone who wishes to use `SigstoreRepository` would be unable to leverage the support for caching you've worked to implement here. This could be resolved by instead specifying a trait bound of AsyncRead + AsyncWrite.

On the subject of AsyncRead + AsyncWrite, the current cache approach of using std::fs::read/write blocks this thread.  Since we're already using tokio in this crate we could pull in its `fs` feature and use their methods help our downstream dependents a bit.

2024-03-02 20:17 UTC, tannaurus commented
I'm afraid that's all I've got for my Saturday morning code review @tnytown . I can circle back around to this review in the coming days 😄 for now I've got myself a new [Playdate](https://play.date/) and a C SDK to go play around with! 🚀

2024-03-09 16:28 UTC, tannaurus commented on src/verify/verifier.rs
> +pub struct Verifier {
At the risk of bikeshedding, I'll just note, with no firm objection nor meaningful skin in this codebase, that I believe having a `sync` module within `verify` is more idiomatic. I personally prefer this because it pulls the context of whether this is sync or async into the "use declaration." Those who are building synchronous projects can find their structs in the `sync` module(s)

I'm interested to hear another person's opinion on this too 🙂

2024-03-09 16:31 UTC, tannaurus commented on src/verify/verifier.rs
> +    /// Constructs an [`AsyncVerifier`] against the public-good trust root.
Is there a thought process behind this not being declared in the other impl? I would expect to see this with some kind of stricter trait bound, but in the absence of that, I'm more curious if there is a motive (even if it's just preferred code style)

2024-03-09 16:48 UTC, tannaurus commented on src/verify/verifier.rs
> +        if !(not_before <= integrated_time && integrated_time <= not_after) {
Is this correct?

I find the named "not_before/after" combined with flipping the bool and `&&` pretty difficult to reason about. 

It feels to me that this could be `not_before > integrated_time && integrated_time > not_after` but there's a non-zero chance my saturday morning not-enough-coffee-brain is just 404ing

Also, it feels like `not_before` should be its own check? "this certificate isn't valid yet" is different than "this certificate was valid for a time but is now expired"

2024-03-09 16:55 UTC, tannaurus commented on src/verify/policy.rs
> +    pub fn new<I: IntoIterator<Item = &'a dyn VerificationPolicy>>(policies: I) -> Option<Self> {
Some general feedback that I hope you're open to

I noticed some inconsistencies in how trait bounds are declared in this PR: sometimes it's `fn my_func<T: SomeTrait>(my_arg: T)` other times it's `fn my_func(my_arg: impl MyTrait)` and other times it's `fn my_func<T>(my_arg: T) -> MyStruct where T: MyTrait`.

I personally like to keep them consistently to the latter (`where` declaration) since that feels like the easiest to read when trait bounds get to be lengthy.

2024-03-09 17:49 UTC, tannaurus commented on src/verify/verifier.rs
> +        let Some(log_entry) = materials.tlog_entry(offline, &input_digest) else {
Suggestion 🙂 
`let log_entry = materials.tlog_entry(offline, &input_digest).ok_or(SignatureErrorKind::Transparency)?;`

2024-03-09 18:55 UTC, tannaurus commented on src/verify/verifier.rs
> +        let mut buf = [0u8; 1024];
I understand the motivation here, I like that this makes reading an "input" easier,  but it presumes the input to implement AsyncRead, which may not be true. It also takes a relatively greedy allocation that the downstream application has no control over. 

In my case I've already deserialized a request that contains the payload that my application must re-construct (multiple values appended to each other in a particular order). I _could_ get my payload to implement AsyncRead, but now the intentions of this decision, making the downstream's life easier, has had the unfortunate side effect of making that implementation more strenuous/awkward.   

Would just expecting this to be a `Vec<u8>` make more sense? It solves the problem of a potentially greed allocation and gives the caller the flexibility to work within the constraints of their system / their input's origin.

2024-04-11 10:29 UTC, flavio commented on src/bundle/mod.rs
> +                version: "0.0.1".to_owned(),
I'm fine with that, we can tackle that later on

2024-04-11 14:22 UTC, flavio requested changes
LGTM, I left some comments.

Aside from my comments, it would be great to see the other comments addressed. For TODO stuff/nodes the outcome of the conversation can be added into the source code as a comment

2024-04-11 14:22 UTC, flavio commented on src/verify/verifier.rs
> +pub struct Verifier {
I like @tannaurus' suggestion

2024-04-12 06:57 UTC, flavio reviewed
I left a minor comment, I'm fine with this PR.

2024-04-12 06:57 UTC, flavio commented on src/trust/sigstore/mod.rs
> +    macro_rules! impl_test {
I understand why you're using this macro, but it makes the tests less readable. You can achieve the same result using the [rstest](https://crates.io/crates/rstest) crate, which is already a dev dependency.

Finally, you can use the [`tokio::test`](https://docs.rs/tokio/latest/tokio/attr.test.html) macro to decorate the unit test, which removes more boilerplate from the test.

I can do the changes afterwards, I understand this PR has been ongoing since a long time

2024-04-12 06:58 UTC, flavio commented
@tannaurus: can you take one last look at the PR before I merge it?

2024-04-17 10:14 UTC, flavio approved these changes
I think we're finally ready to merge it. Sorry for the long time it took!

2024-04-17 10:14 UTC, merged

2024-04-18 16:16 UTC, tannaurus commented
I'm so happy to see this merged! Thanks for all the work @tnytown and @jleightcap ! ❤️ 🚀 

Sorry for my delayed response [here](https://github.com/sigstore/sigstore-rs/pull/311#issuecomment-2051111327). I was out of town for team offsite and then came down with a bug when I got back.