dep: update tough version to v0.16.0
sigstore/sigstore-rs pull request #320
Opened 2023-12-29 06:15 UTC by Xynnn007

Manual for #317.

New version of `tough` brings async impls and also a bug which I am fixing in upstream.

Please DO NOT merge this until the upstream `tough` merges https://github.com/awslabs/tough/pull/737

2024-01-08 14:56 UTC, flavio requested changes
@Xynnn007 thanks for this PR and for the upstream fix.

I've left some comments in the meantime

2024-01-08 14:56 UTC, flavio commented on src/tuf/mod.rs
> +            println!("{data:?}");
nitpick: a leftover, to be removed or turned into a `debug!` statement

2024-01-08 14:56 UTC, flavio commented on src/tuf/mod.rs
> +    trusted_root: OnceLock<TrustedRoot>,
Maybe we should use a [`tokio::sync::OnceCell`](https://docs.rs/tokio/latest/tokio/sync/struct.OnceCell.html) instead?

2024-01-08 14:56 UTC, flavio commented on src/tuf/mod.rs
I think we have to update the inline docs in these points:

* https://github.com/sigstore/sigstore-rs/blob/315d5f676cbaf83d8c1225078524cfc02f89b837/src/tuf/mod.rs#L186-L187
* https://github.com/sigstore/sigstore-rs/blob/315d5f676cbaf83d8c1225078524cfc02f89b837/src/tuf/mod.rs#L210-L211

Now the blocking operations should have be gone. Am I right?

2024-01-09 01:37 UTC, Xynnn007 commented on src/tuf/mod.rs
> +            println!("{data:?}");
Oh. Thanks! Let me delete that

2024-01-09 01:44 UTC, Xynnn007 commented on src/tuf/mod.rs
> +    trusted_root: OnceLock<TrustedRoot>,
Nice suggestion. Let me try this

2024-01-09 01:48 UTC, Xynnn007 commented on src/tuf/mod.rs
Yes. I have double checked comments upon other modified functions. Thanks for pointing out.

2024-01-09 01:59 UTC, Xynnn007 commented
@flavio Thanks for the reviewing. I have fixed them. PTAL

2024-01-09 12:42 UTC, flavio reviewed
LGTM, waiting for the fix done to tough to be merged upstream

2024-01-10 02:31 UTC, Xynnn007 commented
Merged in upstream. Still need to wait for a release

2024-02-23 12:17 UTC, lukehinds commented
Still no new version as yet, would you care to poke the folks upstream again @Xynnn007 ?

2024-02-26 07:34 UTC, Xynnn007 commented
> Still no new version as yet, would you care to poke the folks upstream again @Xynnn007 ?

Yes. Pinged in https://cloud-native.slack.com/archives/C8NMD3QJ3/p1708754342493549

2024-03-22 15:29 UTC, astoycos commented
Hiya @Xynnn007 I took a stab at rebasing this against main (https://github.com/sigstore/sigstore-rs/compare/main...astoycos:sigstore-rs:main) so that I could bring in these blocking changes -> https://github.com/awslabs/tough/pull/755

But I'm a bit stuck on 
```rust
error: future cannot be sent between threads safely
   --> src/trust/sigstore/mod.rs:168:65
    |
168 |       async fn fulcio_certs(&self) -> Result<Vec<CertificateDer>> {
    |  _________________________________________________________________^
169 | |         let root = self.trusted_root().await?;
170 | |
171 | |         // Allow expired certificates: they may have been active when the
...   |
182 | |         }
183 | |     }
    | |_____^ future created by async block is not `Send`
    |
    = help: within `SigstoreTrustRoot`, the trait `Sync` is not implemented for `std::cell::OnceCell<TrustedRoot>`, which is required by `{async block@src/trust/sigstore/mod.rs:168:65: 183:6}: std::marker::Send`
    = note: if you want to do aliasing and mutation between multiple threads, use `std::sync::OnceLock` instead
note: captured value is not `Send` because `&` references cannot be sent unless their referent is `Sync`
   --> src/trust/sigstore/mod.rs:168:28
    |
168 |     async fn fulcio_certs(&self) -> Result<Vec<CertificateDer>> {
    |                            ^^^^ has type `&SigstoreTrustRoot` which is not `Send`, because `SigstoreTrustRoot` is not `Sync`
    = note: required for the cast from `Pin<Box<{async block@src/trust/sigstore/mod.rs:168:65: 183:6}>>` to `Pin<Box<dyn Future<Output = Result<Vec<CertificateDer<'life0>>, SigstoreError>> + Send>>`
    = note: the full name for the type has been written to '/home/astoycos/go/src/github.com/sigstore/sigstore-rs/target/debug/deps/sigstore-00d994436acc6b0d.long-type-9205612641815476395.txt'
    = note: consider using `--verbose` to print the full type name to the console

error: future cannot be sent between threads safely
   --> src/trust/sigstore/mod.rs:189:54
    |
189 |       async fn rekor_keys(&self) -> Result<Vec<&[u8]>> {
    |  ______________________________________________________^
190 | |         let root = self.trusted_root().await?;
191 | |         let keys: Vec<_> = Self::tlog_keys(&root.tlogs).collect();
192 | |
...   |
199 | |         }
200 | |     }
    | |_____^ future created by async block is not `Send`
    |
    = help: within `SigstoreTrustRoot`, the trait `Sync` is not implemented for `std::cell::OnceCell<TrustedRoot>`, which is required by `{async block@src/trust/sigstore/mod.rs:189:54: 200:6}: std::marker::Send`
```

Can you help out with this?

2024-03-22 16:31 UTC, astoycos commented
Well I was able to get things building there ^^ but now 

```rust 
error[E0277]: `dyn sigstore::tuf::Repository` cannot be shared between threads safely
```

Obv now those types referenced above are not `Send` I need to figure out what changed in `tough` to cause this change :/

2024-03-22 17:36 UTC, astoycos commented
Rebased and updated this in https://github.com/sigstore/sigstore-rs/pull/340 hope that's alright @Xynnn007!

2024-03-25 01:30 UTC, Xynnn007 commented
Hi @astoycos I was once planning to update this PR after the upstream `tough` made a new release as we will not merge any PR involving a dep specified by `rev` rather than a `version`.

If you'd like to take this, let me close the PR and assign #317 to you.

2024-03-25 03:22 UTC, astoycos commented
Sure @Xynnn007 I'm happy to carry this through if that's alright with you :) 

I'd like to start contributing to sigstore!

2024-03-25 04:43 UTC, closed without merging

2024-03-25 04:46 UTC, Xynnn007 commented
@astoycos Welcome! Seems that I cannot find you in the asignees. But that does not matter, just go.

2024-03-25 05:07 UTC, astoycos commented
Sounds good If you could give https://github.com/sigstore/sigstore-rs/pull/340 a look to make sure I stated this correctly I'd appreciate it :)