Signed Certificate Timestamp verification
sigstore/sigstore-rs pull request #326
Opened 2024-01-22 22:28 UTC by tnytown

~~Blocked on #311.~~

#### Summary

Adds Signed Certificate Timestamp verification and hooks it up to the bundle signing flow. SCT verification ensures that the signing certificate in a given operation has been submitted to the Certificate Transparency log, which aids in the detection of malicious certificates and keeps Certificate Authorities like Fulcio honest.

#### Release Note

* Implemented Signed Certificate Timestamp validation for certificates used in Sigstore Bundle operations.

#### Documentation

No user-facing documentation needed, we automatically perform SCT validation when public `sign` and `verify` APIs are used.

2024-01-30 08:09 UTC, franziskuskiefer commented on Cargo.toml
> +tls_codec = { git = "https://github.com/RustCrypto/formats", rev = "189b4d0d43c75b5e3ab9031ef0008c7ba9ae9378" }
v0.4.1 has been released with this.

2024-02-02 07:35 UTC, flavio commented on src/crypto/keyring.rs
> +type Result<T> = std::result::Result<T, KeyringError>;
I'm in favor of splitting the error types on a per-module basis. I would still "collect" them into the `SigstoreError` for convenience, but I'm open to revisit this position

2024-06-20 14:34 UTC, flavio requested changes
LGTM, I left two minor suggestions.

2024-06-20 14:34 UTC, flavio commented on src/bundle/sign.rs
> +    #[cfg(feature = "sigstore-trust-root")]
```suggestion
    #[cfg_attr(docsrs, doc(cfg(feature = "sigstore-trust-root")))]
    #[cfg(feature = "sigstore-trust-root")]
```

2024-06-20 14:34 UTC, flavio commented on src/bundle/sign.rs
> +    #[cfg(feature = "sigstore-trust-root")]
```suggestion
    #[cfg_attr(docsrs, doc(cfg(feature = "sigstore-trust-root")))]
    #[cfg(feature = "sigstore-trust-root")]
```

2024-06-20 16:05 UTC, flavio approved these changes

2024-06-20 16:05 UTC, merged