update tough dep
sigstore/sigstore-rs pull request #340
Opened 2024-03-22 17:36 UTC by astoycos

#### Summary

This commit updates the tough dependency, which
changes how many of our trait definitions work.

Additionally move from the use of
 oncecell to oncelock for sigstoretrustroot.trusted_root
so that SigstoreTrustRoot can be Send.

Update examples and tests.

Manual for https://github.com/sigstore/sigstore-rs/pull/317

Fixes #338 

#### Release Note

#### Documentation

2024-03-25 16:46 UTC, astoycos commented
Once https://github.com/awslabs/tough/pull/759 Merges I'll be able to use the tagged release version of tough here 🥳

2024-03-25 16:47 UTC, astoycos commented
cc @Xynnn007 and @kommendorkapten for reviews

2024-03-25 17:53 UTC, astoycos commented
Touch point we're using this downstream in https://github.com/bpfman/bpfman/pull/1042

2024-03-25 22:28 UTC, haydentherapper commented
also cc @flavio

2024-03-26 10:08 UTC, flavio requested changes

2024-03-26 15:58 UTC, astoycos commented on src/trust/mod.rs
> +    async fn fulcio_certs(&self) -> crate::errors::Result<Vec<CertificateDer>> {
I think I did this right, I simply added a build macro to the entire impl to ensure it's not compiled inside of wasm guest code, please let me know if thats right

2024-03-27 08:19 UTC, flavio commented
Great news, a new tough release is out: https://github.com/awslabs/tough/releases/tag/tough-v0.17.1

2024-03-27 08:26 UTC, flavio requested changes
Everything looks good. The `Cargo.toml` file has to be updated to consume the freshly published tough crate.

I'll be happy to merge this PR and tag a new minor release ASAP

2024-03-27 08:26 UTC, flavio commented on Cargo.toml
> +tough = { git = "https://github.com/awslabs/tough" , branch = "develop", features = ["http"], optional = true }
A new release is out :partying_face: https://github.com/awslabs/tough/releases/tag/tough-v0.17.1

2024-03-27 08:26 UTC, flavio commented on src/trust/mod.rs
> +    async fn fulcio_certs(&self) -> crate::errors::Result<Vec<CertificateDer>> {
Everything looks good

2024-03-27 08:26 UTC, flavio commented on src/trust/sigstore/mod.rs
> +
This is really nitpicking, could you move all the external `use` statements together at the top of the file, around line `42`?

2024-03-27 13:39 UTC, astoycos commented on src/trust/sigstore/mod.rs
> +
No worries I understand, good catch, done!

2024-03-27 13:39 UTC, astoycos commented on Cargo.toml
> +tough = { git = "https://github.com/awslabs/tough" , branch = "develop", features = ["http"], optional = true }
Yayyy using it now!

2024-03-27 13:40 UTC, astoycos commented
Thanks for the reviews @flavio!

2024-03-27 14:31 UTC, flavio requested changes
One last minor change

2024-03-27 14:31 UTC, flavio commented on src/trust/sigstore/mod.rs
> +use sha2::{Digest, Sha256};
Sorry to bother, these should go below the inline docs

2024-03-27 14:39 UTC, astoycos commented on src/trust/sigstore/mod.rs
> +use sha2::{Digest, Sha256};
So strange.. `cargo fmt` puts them there 🤣

2024-03-27 14:41 UTC, astoycos commented on src/trust/sigstore/mod.rs
> +use sha2::{Digest, Sha256};
Sorry about that fixed!

2024-03-27 14:56 UTC, flavio commented
I'm waiting for all the tests to be green, then I'll merge it :)

2024-03-27 15:03 UTC, flavio approved these changes
thanks a lot for having handled this upgrade

2024-03-27 15:03 UTC, merged