fix: Allow empty passwords for encrypted pem files
sigstore/sigstore-rs pull request #381
Opened 2024-08-04 05:19 UTC by gmpinder

#### Summary

I've been working on integrating this crate into my CLI program and I ran into a situation where pem files generated by the cosign tool with an empty password couldn't be loaded. I was getting an invalid key type error, so I dug into why that was and found that the keys were being processed differently if the password had no length. Removing that constraint allowed my empty password cosign keys to be loaded properly. I'm hoping this change will be accepted so that this rust implementation is a bit closer to parity with the cosign cli tool.

Closes #380 

#### Release Note

- Allows the use of encrypted PEM files with an empty password to keep in parity with `cosign`

#### Documentation

N/A

2024-08-04 06:40 UTC, gmpinder commented
After doing some more testing, there seems to be another spot that's preventing this from working with empty password cosign generated keys. Working on figuring that out

2024-08-04 07:05 UTC, gmpinder commented
Ok so I found the other issue, there was apparently a hard check for the `N` param for the kdf encryption of the pem. I've removed it for now since cosign appears to use a value of 65536 which is what was causing the key to not be able to be read.

example test cosign pem:

```json
{"kdf":{"name":"scrypt","params":{"N":65536,"r":8,"p":1},"salt":"/67J9VwY8a6ravOCALfO1P3NGD4Xsk6/M9hNbaXC7+A="},"cipher":{"name":"nacl/secretbox","nonce":"/ht529R6XgnAFmUz/u4jyQTMeom4T6MT"},"ciphertext":"ZJYYk2GQaZgJtHzS0JtUnMhSnQWsnGpD3a5B23weYKodDo2dxUNexEIDp88FRC3jURM4b56EHEcnVUZaDL3cgfkN7Meeo18VYSvZmwI7XhRZs119G6yifi8HqZFbgI3mQwNv0EDp1DzL4wfIZ0pyP+xA/3lNy9myfRd6R3RhGHyIkz5QxxrvZ0uTvGTLNrgKHus/sSn+5ZKl/Q=="}
```

2024-08-06 06:45 UTC, flavio requested changes
I'm fine with the changes done to allow empty passwords.

@Xynnn007: would you mind taking a look too?

2024-08-06 06:45 UTC, flavio commented on src/crypto/signing_key/kdf.rs
> +        match self.params.r == SCRYPT_R && self.params.p == SCRYPT_P {
This change isn't related with the main topic of the PR, can you either: move it to a new dedicated PR or move it to a separate commit of this PR?

Moreover, I would prefer to leave the check in place, but update the value we have hard-coded to reflect the new params used by cosign.
I see they are defined [here](https://github.com/sigstore/sigstore-rs/blob/4c7bf8d28be494ab2b76a20c628c6ae63cc3b56b/src/crypto/signing_key/kdf.rs#L35-L42)

While doing that, can you also add a comment pointing to the origin of these values? (a link to the source file and line providing them).

Thanks!

2024-08-06 09:49 UTC, Xynnn007 approved these changes
The logic looks good to me. I relooked inside the cosign code and behavior and ensure that if no password is given, still a encrypted privatekey will be given rather than a plaintext privatekey. The encryption key is derived from `""` with scrypt.

2024-08-06 09:53 UTC, Xynnn007 commented on src/crypto/signing_key/kdf.rs
> +        match self.params.r == SCRYPT_R && self.params.p == SCRYPT_P {
Btw the current cosign code uses N=65536. See underlying code here https://github.com/secure-systems-lab/go-securesystemslib/blob/main/encrypted/encrypted.go#L206C63-L206C71

2024-08-06 18:12 UTC, loosebazooka commented
@woodruffw brought this up in the sigstore clients meeting today. Two points to consider here:
1. Empty password vs unencrypted: Empty password may lead to a assumption of stronger security
2. Should sigstore-rs even be generating long lived keys (and serializing them to PEM)? Should this instead be the job of another tool?

2024-08-06 18:49 UTC, gmpinder commented on src/crypto/signing_key/kdf.rs
> +        match self.params.r == SCRYPT_R && self.params.p == SCRYPT_P {
Sure, I can pull that change out into another PR

2024-08-06 18:51 UTC, gmpinder commented on src/crypto/signing_key/kdf.rs
> +        match self.params.r == SCRYPT_R && self.params.p == SCRYPT_P {
Another consideration. If I change the value entirely, previously generated PEM files would fail to get loaded. We could try instead having 2 constants and check for the current N value and the N value used by cosign.

2024-08-06 19:10 UTC, gmpinder commented on src/crypto/signing_key/kdf.rs
> +        match self.params.r == SCRYPT_R && self.params.p == SCRYPT_P {
Ok so figuring out how to make a new PR from the same fork was too much, so I just split them into 2 separate commits

2024-08-07 12:42 UTC, gmpinder commented
> (Thanks @loosebazooka! I forgot to comment on this earlier.)
> 
> > * Empty password vs unencrypted: Empty password may lead to a assumption of stronger security
> 
> To elaborate a bit more on this concern: IMO there's a security risk with enabling people to encrypt with the empty password, insofar as the "encrypted" version is indistinguishable from a version with an actual, strong password. In other words: a user who lacks a full picture of the system may assume that any PEM blob with the `BEGIN ENCRYPTED SIGSTORE PRIVATE KEY` tag is safe to leak/commit to a public source, without realizing that the encryption is effectively nonexistent.
> 
> I think the "fix" involves both `cosign` and `sigstore-rs`:
> 
> 1. It looks like `sigstore-rs` (and maybe `cosign` too?) generates key-bearing PEMs with the `ENCRYPTED` tag unconditionally, even when the private key isn't actually encrypted. When the key is actually unencrypted, the PEM tag probably shouldn't include that marker.
> 2. Rather than encrypting with an empty password (when an empty one is explicitly provided), IMO `sigstore-rs` and `cosign` should refuse the operation and fail.
> 
> (2) is arguably a slippery slope towards "weak" password/entropy testing, which is an anti-pattern. But IMO stopping at empty passwords is perfectly fine; that's the point of having a strong memory-hard hash function like `scrypt` 🙂 

What would happen to the users who have already generated a cosign key with an empty password? Would that just stop working all of a sudden? Would those users then have to create new keys and then update their users to know that they have a different key? I feel like changing that now could break compatibility with previous use cases.

2024-08-07 14:41 UTC, woodruffw commented
> What would happen to the users who have already generated a cosign key with an empty password?

There would definitely need to be a transition period here, at least for `cosign` (since AFAIK they follow strict SemVer). Maybe something like this:

1. Loading empty-password keys continues to work, with a warning, until the next major version (3.x), when it becomes a failure.
2. Generating empty-password keys becomes a hard error immediately, since `cosign generate-key-pair` is already allowed to fail as part of its invocation contract

For `sigstore-rs`, I don't think a transition period is needed: the project is still explicitly under active development and is not considered stable. 

Do you think that would accomodate your use case?

2024-08-07 21:51 UTC, gmpinder commented
> Do you think that would accomodate your use case?

Not really as we have hundreds of users of our system that has been relying on using those empty cosign passwords. I don't see why breaking user-space to remove something that `cosign` allows in the first place is a good idea. If the `cosign` team wants to make that breaking change, then so be it. Until then, I think `sigstore-rs` should at least accommodate the use-cases that `cosign` has created just so that interoperability can exist, because otherwise we will have to stop using this library altogether so that we don't break our user's builds.

2024-08-07 23:44 UTC, Xynnn007 commented
For compatibility, we probably can judge the reading logic of the keys by pem header, s.t.

1. if the private key starts with `SIGSTORE ...` and no password is given, will use empty password to derive key to decrypt
2. if the private key starts with `PRIVATE ...` and no password is given, it will be treated as a plaintext key
3. if the private key starts with `SIGSTORE ...` and some password is given, will use the password to derive key to decrypt
4. if the private key starts with `PRIVATE ...` and some password is given, will raise an error to show that the key is not encrypted.

case 2is for compability

2024-08-20 13:40 UTC, gmpinder commented
Any update on whether this will be merged in?

2024-08-21 01:30 UTC, Xynnn007 reviewed
Thanks for this! More comments about code style.

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ecdsa/ec.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(private_key),
We'd better add another case for `PRIVATE_KEY_PEM_LABEL if !password.is_empty()` to explicitly show the error. Or it will fall on `Unsupported pem tag {PRIVATE_KEY_PEM_LABEL}`

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ecdsa/ec.rs
> +    fn ecdsa_from_encrypted_pem_cosign_empty_password() {
We might combined this case with `ecdsa_from_encrypted_pem` using `rstest`, s.t.
```rust
#[rstest]
#[case("tests/data/keys/ecdsa_encrypted_private.key", PASSWORD)]
#[case::empty_password("tests/data/keys/cosign_generated_encrypted_empty_private.key", EMPTY_PASSWORD)]
fn ecdsa_from_encrypted_pem(#[case] keypath: &str, #[case] password: &str) {
...
}
```

This would help to keep the tests more dry

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ecdsa/ec.rs
> +    fn ecdsa_to_encrypted_pem_empty_password() {
ditto with `ecdsa_to_and_from_encrypted_pem`

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ed25519.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(encrypted_pem),
ditto, for `PRIVATE_KEY_PEM_LABEL if !password.is_empty()`

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ed25519.rs
> +    fn ed25519_from_unencrypted_pem_empty_password() {
ditto

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ed25519.rs
> +    fn ed25519_to_encrypted_pem_empty_password() {
ditto

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/ed25519.rs
> +    fn ed25519_to_and_from_encrypted_pem_empty_password() {
ditto

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/rsa/keypair.rs
> +            }
Ok, we might also ned to add case for `PRIVATE_KEY_PEM_LABEL if !password.is_empty()` here to tell that not supported `PRIVATE_KEY_PEM_LABEL` with password

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/rsa/keypair.rs
> +    fn rsa_from_unencrypted_pem_empty_password() {
ditto, merge with `rsa_from_unencrypted_pem`

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/rsa/keypair.rs
> +    fn rsa_to_encrypted_pem_empty_password() {
ditto, merge with `rsa_to_encrypted_pem`

2024-08-21 01:30 UTC, Xynnn007 commented on src/crypto/signing_key/rsa/keypair.rs
> +    fn rsa_to_and_from_encrypted_pem_empty_password() {
please merge with `rsa_to_and_from_encrypted_pem`

2024-08-21 05:09 UTC, gmpinder commented
Cool, I can work on these this weekend

2024-08-24 02:18 UTC, gmpinder commented
Alright, got the tests updated.

2024-08-26 07:05 UTC, Xynnn007 commented on src/crypto/signing_key/ecdsa/ec.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(private_key),
This comment seems not to have been fixed. What I mean is to add another case
```
PRIVATE_KEY_PEM_LABEL if !password.is_empty() => Err(SigstoreError::PrivateKeyDecryptError(format!(
                "Unencrypted private key but password provided"
            ))),
```

Or, just raise a warning and ignore the password

2024-08-26 07:05 UTC, Xynnn007 commented on src/crypto/signing_key/ed25519.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(encrypted_pem),
Also for this, not resolved.

2024-09-01 18:00 UTC, gmpinder commented on src/crypto/signing_key/ecdsa/ec.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(private_key),
My bad, fixing this

2024-09-01 18:17 UTC, gmpinder commented on src/crypto/signing_key/ecdsa/ec.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(private_key),
Done!

2024-09-01 18:17 UTC, gmpinder commented on src/crypto/signing_key/ed25519.rs
> +            PRIVATE_KEY_PEM_LABEL if password.is_empty() => Self::from_pem(encrypted_pem),
Fixed

2024-09-01 18:17 UTC, gmpinder commented
Got the last few comments resolved

2024-09-02 06:13 UTC, Xynnn007 commented
@gmpinder Thanks for your adopting the suggestions! Let's see how CI works

2024-09-02 06:22 UTC, Xynnn007 commented
Good. Passed

2024-09-02 06:22 UTC, Xynnn007 approved these changes
LGTM. ptal @flavio

2024-09-03 09:41 UTC, flavio approved these changes

2024-09-03 09:41 UTC, merged

2024-09-03 16:34 UTC, gmpinder commented
Awesome! Would you be able to get these changes out in a `v0.9.1` patch so my crate is able to make use of it?

2024-09-11 10:28 UTC, flavio commented
@gmpinder JFYI, this is going to be part of 0.10.0, which we expect to release soon (see https://github.com/sigstore/sigstore-rs/pull/391)