fix!: Drop filter_signature_layers() for filter_constraints()
sigstore/sigstore-rs pull request #42
Opened 2022-03-04 12:52 UTC by viccuad

#### Summary

BREAKING CHANGE: Drop `cosign::filter_signature_layers` in favour of
`cosign::filter_constraints()`, that returns unsatisfied constraints
instead.

The relationship between layers and constraints is not injective (e.g:
AnnotationsVerifier), hence no image verification info could be derived
from the number of layers verified.

With unsatisfied constraints, we know that 0 means the image is
verified.
If we have some unsatisfied constraints, we can use them to provide info
on why we failed verification.

Add a test and consume changes.

TODO: Make VerificationConstraint implement `std::fmt:Display`, `serde::ser::Serialize`, or both. This way information on why verification failed can be printed to users or consumed in json.

#### Ticket Link

Fixes https://github.com/sigstore/sigstore-rs/issues/41.

#### Release Note

```release-note
TODO
```

2022-03-04 12:55 UTC, viccuad commented on examples/verify/main.rs
> +                println!("{:?}", unsatisfied_constraints);
See TODO.
I'm undecided on how to continue here. Making `VerificationConstraint` Serializable seems doable (apart from working with boxed dyns..). The only hiccup is `ring::signature::VerificationAlgorithm` used in `PublicKeyVerifier`.

2022-03-04 13:19 UTC, viccuad commented on src/cosign/mod.rs
> +) -> Result<VerificationConstraintVec> {
I decided to not return the `SignatureLayers` that passed verification (or failed, neither), as I didn't see much value in having them, without having the associated list of satisfied or unsatisfied constraints to them.

That said, it would be easy to just construct a couple of vectors with the Layers in the already existing iterations, and it wouldn't change the complexity in time.

If wanted, we could return instead a 2d matrix that maps the relationship between layers and constraints (if a constraint has no associated layers there, is unsatisfied. If any constraint is unsatisfied, the verification fails).

2022-03-08 08:51 UTC, viccuad commented on examples/verify/main.rs
> +                println!("{:?}", unsatisfied_constraints);
Went with `Result<(),SigstoreFilterConstraintsError>`, see https://github.com/sigstore/sigstore-rs/pull/42/commits/34db8715bf0023bad652a60add2b8c4192e0db1a.

2022-03-08 08:51 UTC, viccuad commented on src/cosign/mod.rs
> +) -> Result<VerificationConstraintVec> {
Went with `Result<(),SigstoreFilterConstraintsError>`, see https://github.com/sigstore/sigstore-rs/pull/42/commits/34db8715bf0023bad652a60add2b8c4192e0db1a.

2022-03-08 09:12 UTC, flavio requested changes
LGTM, thanks for the hard work. I left some small comments to be addressed

2022-03-08 09:12 UTC, flavio commented on src/cosign/mod.rs
> +/// references to unsatisfied constraints.
```suggestion
/// Returns a `Result` with either `Ok()` for passed verification or
/// [`SigstoreFilterConstraintsError`](crate::errors::SigstoreFilterConstraintsError), which contains a vector of
/// references to unsatisfied constraints.
```

I improved the formatting, the link should work too. Double check by running `cargo doc --open`

2022-03-08 09:12 UTC, flavio commented on src/cosign/mod.rs
> +    let unsatisfied_constraints: Vec<&Box<dyn VerificationConstraint>> = constraints.filter(|c| {
Here we can replace `Vec<&Box<dyn VerificationConstraint>>` with the custom type `VerificationConstraintRefVec` we defined

2022-03-08 09:12 UTC, flavio commented on src/cosign/mod.rs
> +    if unsatisfied_constraints.is_empty() {
nitpicking, maybe add an empty line?

2022-03-08 09:12 UTC, flavio commented on src/cosign/mod.rs
> +            issuer: None, // missing issuer
```suggestion
            issuer: None, // missing issuer - makes check more relaxed
```

The missing issuer per se, is not an error. This makes the verifier more relaxed. I've added the little clarification to ensure other readers don't assume this could lead to a verification == false

2022-03-08 09:12 UTC, flavio commented on src/cosign/mod.rs
> +pub fn filter_constraints<'a, 'b, I>(
As discussed via chat, we both agreed to go on with `verify_constraints`, which might return a `SigstoreVerifyConstraintsError`

2022-03-08 09:22 UTC, viccuad commented on src/cosign/mod.rs
> +pub fn filter_constraints<'a, 'b, I>(
Done via force-push, since commit contents needed to change too.

2022-03-08 09:45 UTC, viccuad commented on examples/verify/main.rs
> +async fn run_app() -> anyhow::Result<(Vec<SignatureLayer>, Vec<Box<dyn VerificationConstraint>>)> {
True! done in https://github.com/sigstore/sigstore-rs/pull/42/commits/9f56fd64da567c8b0ebabf9d090717887e38f86f.

2022-03-08 09:46 UTC, viccuad commented on src/cosign/mod.rs
> +use self::verification_constraint::VerificationConstraint;
True! done in https://github.com/sigstore/sigstore-rs/pull/42/commits/9f56fd64da567c8b0ebabf9d090717887e38f86f.

2022-03-08 09:46 UTC, viccuad commented on src/cosign/mod.rs
> +/// references to unsatisfied constraints.
Oh, good point! Fixed that one (and another one), and added `cargo doc` as part of `make test` in https://github.com/sigstore/sigstore-rs/pull/42/commits/167114e21b7590569d878ed3126e4349ea5ea01b.

2022-03-08 09:47 UTC, viccuad commented on src/cosign/mod.rs
> +    let unsatisfied_constraints: Vec<&Box<dyn VerificationConstraint>> = constraints.filter(|c| {
True! done in https://github.com/sigstore/sigstore-rs/pull/42/commits/9f56fd64da567c8b0ebabf9d090717887e38f86f.

2022-03-08 09:47 UTC, viccuad commented on src/cosign/mod.rs
> +    if unsatisfied_constraints.is_empty() {
True! done in https://github.com/sigstore/sigstore-rs/pull/42/commits/9f56fd64da567c8b0ebabf9d090717887e38f86f.

2022-03-08 09:47 UTC, viccuad commented on src/cosign/mod.rs
> +            issuer: None, // missing issuer
True! done in https://github.com/sigstore/sigstore-rs/pull/42/commits/9f56fd64da567c8b0ebabf9d090717887e38f86f.

2022-03-08 10:10 UTC, flavio approved these changes
LGTM. Thanks for the fixes

2022-03-08 10:14 UTC, flavio requested changes
Last comment, I promise :)

2022-03-08 10:14 UTC, flavio commented on src/lib.rs
> +//!           } else {
In theory this should never happen. How could we end up having an empty list of unsatisfied constraints? I would remove this code block by dropping the `if/else` and use just what is currently into the `else` block

2022-03-08 10:14 UTC, flavio commented on src/lib.rs
> +//!   // the image
```suggestion
Use the given list of constraints to verify the trusted `signature_layers`. This will raise an error if one or more verification constraints are not satisfied.

2022-03-08 11:35 UTC, viccuad commented on src/lib.rs
> +//!           } else {
true, good point. Fixed in https://github.com/sigstore/sigstore-rs/pull/42/commits/261c904a406d2b98ad021ee733ecded84dd32cbc.

2022-03-08 11:35 UTC, viccuad commented on src/lib.rs
> +//!   // the image
Fixed in https://github.com/sigstore/sigstore-rs/pull/42/commits/261c904a406d2b98ad021ee733ecded84dd32cbc.

2022-03-08 12:31 UTC, flavio approved these changes
Everything looks good, thanks!

2022-03-08 12:31 UTC, merged